### ISSUE TITLE
404 API Documentation link in README

### ISSUE THREAD

**Issue by shhavel** [evercam/evercam-ruby#12]
Link https://github.com/evercam/evercam-api/wiki in `README.md` leads to 404 page,
probably github repository `evercam/evercam-api` became private or was moved.

Thanks

**Comment by ijunaidfarooq** [comment]
@shhavel Yeah its been removed. Our new API is https://github.com/evercam/evercam-media.

Thanks for the notice. I have replaced it in there as well.
